server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    continue-on-error: false
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include:
            - health
            - info
            - metrics
            - prometheus
  jpa:
    hibernate:
      ddl-auto: create
    database: H2
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch-size: 400
          lob:
            non_contextual_creation: true
        format_sql: false
        order_inserts: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    enabled: false
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
# ========= Logging ========== #
#logging:
#  level:
#    root: ERROR
#    com:
#      example:
#        documentmanagement: DEBUG
# ========= Swagger ========== #
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

    swagger-ui:
      base-url: localhost:8080/api
